export const users = [
  {
    _id: "1",
    username: "john_doe",
    name: "John Doe",
    password: "password123",
    profilePicture: "profile1.jpg",
    gender: "male",
  },
  {
    _id: "2",
    username: "jane_doe",
    name: "Jane Doe",
    password: "password123",
    profilePicture: "profile2.jpg",
    gender: "female",
  },
  {
    _id: "3",
    username: "sam_smith",
    name: "Sam Smith",
    password: "password123",
    profilePicture: "profile3.jpg",
    gender: "male",
  },
  {
    _id: "4",
    username: "lisa_jones",
    name: "Lisa Jones",
    password: "password123",
    profilePicture: "profile4.jpg",
    gender: "female",
  },
  {
    _id: "5",
    username: "mike_brown",
    name: "Mike Brown",
    password: "password123",
    profilePicture: "profile5.jpg",
    gender: "male",
  },
  {
    _id: "6",
    username: "emily_white",
    name: "Emily White",
    password: "password123",
    profilePicture: "profile6.jpg",
    gender: "female",
  },
  {
    _id: "7",
    username: "david_clark",
    name: "David Clark",
    password: "password123",
    profilePicture: "profile7.jpg",
    gender: "male",
  },
  {
    _id: "8",
    username: "sarah_miller",
    name: "Sarah Miller",
    password: "password123",
    profilePicture: "profile8.jpg",
    gender: "female",
  },
  {
    _id: "9",
    username: "chris_wilson",
    name: "Chris Wilson",
    password: "password123",
    profilePicture: "profile9.jpg",
    gender: "male",
  },
  {
    _id: "10",
    username: "anna_taylor",
    name: "Anna Taylor",
    password: "password123",
    profilePicture: "profile10.jpg",
    gender: "female",
  },
];

export const transactions = [
  {
    _id: "1",
    userId: "1",
    description: "Grocery shopping",
    paymentType: "credit card",
    category: "Food",
    amount: 50.75,
    location: "Supermarket",
    date: "2023-01-01",
  },
  {
    _id: "2",
    userId: "2",
    description: "Gas refill",
    paymentType: "debit card",
    category: "Transport",
    amount: 30.0,
    location: "Gas Station",
    date: "2023-01-02",
  },
  {
    _id: "3",
    userId: "3",
    description: "Dinner at restaurant",
    paymentType: "cash",
    category: "Food",
    amount: 75.5,
    location: "Restaurant",
    date: "2023-01-03",
  },
  {
    _id: "4",
    userId: "4",
    description: "Monthly rent",
    paymentType: "bank transfer",
    category: "Housing",
    amount: 1200.0,
    location: "Apartment",
    date: "2023-01-04",
  },
  {
    _id: "5",
    userId: "5",
    description: "Gym membership",
    paymentType: "credit card",
    category: "Health",
    amount: 45.0,
    location: "Gym",
    date: "2023-01-05",
  },
  {
    _id: "6",
    userId: "6",
    description: "Movie tickets",
    paymentType: "cash",
    category: "Entertainment",
    amount: 25.0,
    location: "Cinema",
    date: "2023-01-06",
  },
  {
    _id: "7",
    userId: "7",
    description: "Electricity bill",
    paymentType: "debit card",
    category: "Utilities",
    amount: 60.0,
    location: "Home",
    date: "2023-01-07",
  },
  {
    _id: "8",
    userId: "8",
    description: "New shoes",
    paymentType: "credit card",
    category: "Clothing",
    amount: 80.0,
    location: "Mall",
    date: "2023-01-08",
  },
  {
    _id: "9",
    userId: "9",
    description: "Coffee",
    paymentType: "cash",
    category: "Food",
    amount: 5.0,
    location: "Cafe",
    date: "2023-01-09",
  },
  {
    _id: "10",
    userId: "10",
    description: "Online course",
    paymentType: "credit card",
    category: "Education",
    amount: 100.0,
    location: "Online",
    date: "2023-01-10",
  },
  {
    _id: "11",
    userId: "1",
    description: "Phone bill",
    paymentType: "debit card",
    category: "Utilities",
    amount: 40.0,
    location: "Home",
    date: "2023-01-11",
  },
  {
    _id: "12",
    userId: "2",
    description: "Groceries",
    paymentType: "credit card",
    category: "Food",
    amount: 60.0,
    location: "Supermarket",
    date: "2023-01-12",
  },
  {
    _id: "13",
    userId: "3",
    description: "Taxi fare",
    paymentType: "cash",
    category: "Transport",
    amount: 20.0,
    location: "City",
    date: "2023-01-13",
  },
  {
    _id: "14",
    userId: "4",
    description: "Concert tickets",
    paymentType: "credit card",
    category: "Entertainment",
    amount: 150.0,
    location: "Stadium",
    date: "2023-01-14",
  },
  {
    _id: "15",
    userId: "5",
    description: "Books",
    paymentType: "debit card",
    category: "Education",
    amount: 35.0,
    location: "Bookstore",
    date: "2023-01-15",
  },
  {
    _id: "16",
    userId: "6",
    description: "Lunch",
    paymentType: "cash",
    category: "Food",
    amount: 12.0,
    location: "Cafe",
    date: "2023-01-16",
  },
  {
    _id: "17",
    userId: "7",
    description: "Car maintenance",
    paymentType: "credit card",
    category: "Transport",
    amount: 200.0,
    location: "Garage",
    date: "2023-01-17",
  },
  {
    _id: "18",
    userId: "8",
    description: "Haircut",
    paymentType: "cash",
    category: "Personal Care",
    amount: 25.0,
    location: "Salon",
    date: "2023-01-18",
  },
  {
    _id: "19",
    userId: "9",
    description: "Dinner",
    paymentType: "credit card",
    category: "Food",
    amount: 50.0,
    location: "Restaurant",
    date: "2023-01-19",
  },
  {
    _id: "20",
    userId: "10",
    description: "Flight tickets",
    paymentType: "credit card",
    category: "Travel",
    amount: 300.0,
    location: "Airport",
    date: "2023-01-20",
  },
];
